"""add performance indexes

Revision ID: d3439c9f497c
Revises: 5d1ab6d0638d
Create Date: 2026-02-26 05:11:49.852862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3439c9f497c'
down_revision: Union[str, Sequence[str], None] = '5d1ab6d0638d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_alerts_pond_time', 'alerts', ['pond_id', 'timestamp'], unique=False)
    op.create_index('idx_forecast_pond_time', 'forecast_logs', ['pond_id', 'forecast_for'], unique=False)
    op.create_index('idx_clean_pond_timestamp', 'sensor_data_clean', ['pond_id', 'timestamp'], unique=False)
    op.create_index('idx_raw_pond_timestamp', 'sensor_data_raw', ['pond_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_raw_pond_timestamp', table_name='sensor_data_raw')
    op.drop_index('idx_clean_pond_timestamp', table_name='sensor_data_clean')
    op.drop_index('idx_forecast_pond_time', table_name='forecast_logs')
    op.drop_index('idx_alerts_pond_time', table_name='alerts')
    # ### end Alembic commands ###
