"""replace water_quality_logs with raw-clean-forecast-alert tables

Revision ID: e53490f70a66
Revises: b81147dbaf65
Create Date: 2026-02-25 22:29:53.619709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e53490f70a66'
down_revision: Union[str, Sequence[str], None] = 'b81147dbaf65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pond_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pond_id'], ['ponds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecast_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pond_id', sa.UUID(), nullable=False),
    sa.Column('forecast_block_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forecast_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon_step', sa.Integer(), nullable=False),
    sa.Column('pred_do', sa.Float(), nullable=True),
    sa.Column('pred_temperature', sa.Float(), nullable=True),
    sa.Column('pred_ph', sa.Float(), nullable=True),
    sa.Column('pred_turbidity', sa.Float(), nullable=True),
    sa.Column('pred_ammonia', sa.Float(), nullable=True),
    sa.Column('pred_nitrate', sa.Float(), nullable=True),
    sa.Column('actual_do', sa.Float(), nullable=True),
    sa.Column('actual_temperature', sa.Float(), nullable=True),
    sa.Column('actual_ph', sa.Float(), nullable=True),
    sa.Column('actual_turbidity', sa.Float(), nullable=True),
    sa.Column('actual_ammonia', sa.Float(), nullable=True),
    sa.Column('actual_nitrate', sa.Float(), nullable=True),
    sa.Column('risk_state', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pond_id'], ['ponds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_data_raw',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pond_id', sa.UUID(), nullable=False),
    sa.Column('do', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('turbidity', sa.Float(), nullable=True),
    sa.Column('ammonia', sa.Float(), nullable=True),
    sa.Column('nitrate', sa.Float(), nullable=True),
    sa.Column('manganese', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pond_id'], ['ponds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_data_clean',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pond_id', sa.UUID(), nullable=False),
    sa.Column('raw_id', sa.UUID(), nullable=True),
    sa.Column('do', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('turbidity', sa.Float(), nullable=True),
    sa.Column('ammonia', sa.Float(), nullable=True),
    sa.Column('nitrate', sa.Float(), nullable=True),
    sa.Column('manganese', sa.Float(), nullable=True),
    sa.Column('is_imputed', sa.Boolean(), nullable=True),
    sa.Column('quality_flag', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pond_id'], ['ponds.id'], ),
    sa.ForeignKeyConstraint(['raw_id'], ['sensor_data_raw.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_water_quality_logs_id'), table_name='water_quality_logs')
    op.drop_table('water_quality_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_quality_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pond_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('do', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('turbidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ammonia', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('nitrate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('manganese', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pond_id'], ['ponds.id'], name=op.f('water_quality_logs_pond_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('water_quality_logs_pkey'))
    )
    op.create_index(op.f('ix_water_quality_logs_id'), 'water_quality_logs', ['id'], unique=False)
    op.drop_table('sensor_data_clean')
    op.drop_table('sensor_data_raw')
    op.drop_table('forecast_logs')
    op.drop_table('alerts')
    # ### end Alembic commands ###
